name: "Criterion Compare PRs"
description: "Run Criterion against PRs"
inputs:
  token:
    description: "Github Token required to upload to the PR"
    required: true
    default: ""
  cwd:
    description: "Sets the directory to run the benchmarks, relative to the project directory"
    required: false
    default: ""
  token:
    description: "Branch to compare against"
    required: false
    default: "master"
runs:
  using: "node12"
  main: "dist/index.js"
